spring:
  datasource:
      #url: jdbc:h2:tcp://localhost/~/toyProject2
      #username: sa
      #passowrd:
      #driver-class-name: org.h2.Driver
    url: jdbc:mariadb://192.168.0.6:3306/ToyProject2
    username: sorry
    password: rlawltjd39
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      # show_sql: true
      format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace